const [ANGER, SADNESS, SURPRISE, JOY, LOVE, FEAR] = [
  'anger',
  'sad',
  'surprise',
  'joy',
  'love',
  'fear'
]

const NEGATIVE = [ANGER, SADNESS]
const UNKNOWN = 'unknown'

// Maybe add 'unhealthy', 'uncertainty'?
// Check spelling of all emoji

const emotionTypes = {
  imp: [ANGER],
  fu: [ANGER],
  pouting_cat: [ANGER],
  rage: [ANGER],
  angry: [ANGER],
  anguished: [FEAR],
  broken_heart: NEGATIVE,
  shit: NEGATIVE,
  scream: [FEAR],
  scream_cat: [FEAR],
  smiling_imp: UNKNOWN,
  sob: [SADNESS],
  worried: [FEAR],
  thumbsdown: NEGATIVE,
  cold_sweat: [FEAR],
  confounded: [ANGER],
  confused: [SADNESS],
  cry: [SADNESS],
  crying_cat_face: [SADNESS],
  disappointed: [SADNESS],
  face_with_head_bandage: [SADNESS],
  fearful: [FEAR],
  flushed: [FEAR],
  frowning_face: [SADNESS],
  grimacing: [UNKNOWN],
  lying_face: [UNKNOWN],
  nauseated_face: NEGATIVE,
  open_mouth: [SURPRISE],
  persevere: [SADNESS],
  skull: [ANGER],
  skull_and_crossbones: [ANGER],
  sneezing_face: [SADNESS],
  tired_face: [SADNESS],
  unamused: [ANGER],
  weary: [SADNESS],
  disappointed_relieved: [SADNESS],
  dizzy_face: [SURPRISE],
  face_with_thermometer: [SADNESS],
  punch: [ANGER, JOY],
  frowning: [SURPRISE],
  ghost: [FEAR],
  hushed: [FEAR],
  mask: [SADNESS],
  nerd_face: UNKNOWN,
  pensive: [SADNESS],
  roll_eyes: UNKNOWN,
  slightly_frowning_face: [SADNESS],
  stuck_out_tongue_winking_eye: [JOY],
  sweat: [SADNESS],
  thinking: [UNKNOWN],
  zipper_mouth_face: [UNKNOWN],
  clown_face: [UNKNOWN],
  drooling_face: [JOY],
  expressionless: [UNKNOWN],
  money_mouth_face: [UNKNOWN],
  neutral_face: [UNKNOWN],
  no_mouth: [UNKNOWN],
  sleeping: [UNKNOWN],
  sleepy: [UNKNOWN],
  stuck_out_tongue_closed_eyes: [UNKNOWN],
  triumph: [ANGER, JOY],
  upside_down_face: [UNKNOWN],
  handshake: [JOY],
  laughing: [JOY],
  pray: [JOY],
  slightly_smiling_face: [JOY],
  stuck_out_tongue: [JOY],
  sunglasses: [JOY],
  thumbsup: [JOY, LOVE],
  astonished: [SURPRISE],
  blush: [JOY, LOVE],
  cowboy_hat_face: [JOY],
  crossed_fingers: [JOY],
  grin: [JOY],
  grinning: [JOY],
  hugs: [JOY, LOVE],
  kiss: [LOVE],
  kissing: [LOVE],
  kissing_cat: [LOVE],
  kissing_closed_eyes: [LOVE],
  kissing_smiling_eyes: [LOVE],
  lips: [LOVE],
  ok_hand: [JOY],
  relaxed: [JOY],
  relieved: [JOY],
  smile: [JOY],
  smile_cat: [JOY],
  smiley: [JOY],
  smiley_cat: [JOY],
  smirk: [LOVE],
  smirk_cat: [LOVE],
  sweat_smile: [JOY],
  v: [JOY],
  '100': [JOY],
  black_heart: [LOVE],
  blue_heart: [LOVE],
  clap: [JOY],
  cupid: [LOVE],
  gift_heart: [LOVE],
  green_heart: [LOVE],
  heart: [LOVE],
  heart_eyes: [LOVE],
  heart_eyes_cat: [LOVE],
  heartbeat: [LOVE],
  heartpulse: [LOVE],
  innocent: [JOY],
  joy: [JOY],
  joy_cat: [JOY],
  kissing_heart: [LOVE],
  purple_heart: [LOVE],
  revolving_hearts: [LOVE],
  sparkling_heart: [LOVE],
  two_hearts: [LOVE],
  wink: [LOVE],
  yellow_heart: [LOVE],
  yum: [JOY],
  raised_hands: [JOY],
  rofl: [JOY]
}

// Map emotions to tensor emotions

const emotions_angry = [
  'agressive',
  'angry',
  'annoyed',
  'betrayed',
  'bitter',
  'critical',
  'dismissive',
  'bitter',
  'critical',
  'dismissive',
  'disrespected',
  'distant',
  'frustrated',
  'furious',
  'hostile',
  'humiliated',
  'indignant',
  'infuriated',
  'jealous',
  'let down',
  'mad',
  'numb',
  'provoked',
  'resentful',
  'ridiculed',
  'sceptical',
  'violated',
  'withdrawn'
]

const emotions_bad = [
  'apathetic',
  'bad',
  'bored',
  'busy',
  'indifferent',
  'out of control',
  'overwhelmed',
  'pressured',
  'rushed',
  'sleepy',
  'stressed',
  'tired',
  'unfocussed'
]

const emotions_disgusted = [
  'appalled',
  'awful',
  'detestable',
  'disgusted',
  'dissapointed',
  'dissaproving',
  'embarrassed',
  'hesitant',
  'horrified',
  'judgemental',
  'nauseated',
  'repelled',
  'revolted'
]

const emotions_fearful = [
  'anxious',
  'excluded',
  'exposed',
  'fearful',
  'frightened',
  'helpless',
  'inadequate',
  'inferior',
  'insecure',
  'insignificant',
  'nervous',
  'overwhelmed',
  'persecuted',
  'rejected',
  'scared',
  'threathened',
  'weak',
  'worried',
  'worthless'
]

const emotions_happy = [
  'accepted',
  'aroused',
  'cheeky',
  'confident',
  'content',
  'courageous',
  'creative',
  'curious',
  'free',
  'happy',
  'hopeful',
  'inquiditive',
  'inspired',
  'interested',
  'intimate',
  'joyful',
  'loving',
  'optimistic',
  'peaceful',
  'playful',
  'powerful',
  'proud',
  'respected',
  'sensitive',
  'successful',
  'thankfu;',
  'trusting',
  'valued'
]

const emotions_sad = [
  'abandoned',
  'ashamed',
  'depressed',
  'despair',
  'dissapointed',
  'embarrassed',
  'empty',
  'fragile',
  'grief',
  'guilty',
  'hurt',
  'inferior',
  'isolated',
  'lonely',
  'powerless',
  'remorseful',
  'sad',
  'victimised',
  'vunerable'
]

const emotions_surprised = [
  'amazed',
  'astonished',
  'awe',
  'confused',
  'disillusioned',
  'dismayed',
  'eager',
  'energetic',
  'excited',
  'perplexed',
  'shocked',
  'startled',
  'surprised'
]

module.exports = {
  emotionTypes,
  emotions_angry,
  emotions_bad,
  emotions_disgusted,
  emotions_fearful,
  emotions_happy,
  emotions_sad,
  emotions_surprised
}
